### ISSUE TITLE
Private AKS Cluster

### ISSUE THREAD

**Issue by DavidDury** [paolosalvatori/aks-openai-terraform#1]
Hi Paolo,

Thanks for this solution is really nice! As I can see the AKS cluster is not private, what changes will I need to do to make this private? Maybe deploy bastion and jump machine after to be able to manage the cluster using kubectl, etc.

-David

**Comment by paolosalvatori** [comment]
Just set the `private_cluster_enabled` variable to `true`. For more information, see the AKS terraform module at https://github.com/Azure-Samples/aks-openai-terraform/blob/main/terraform/modules/aks/main.tf. Please let me know if this answers your question. If yes, please close the issue, thanks!

**Comment by DavidDury** [comment]
Thanks appreciated!
